ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.puregoldbe.ibms.MonitoringKt.configureMonitoring
      - com.puregoldbe.ibms.SerializationKt.configureSerialization
      - com.puregoldbe.ibms.RoutingKt.configureRouting
      - com.puregoldbe.ibms.infrastructure.BootstrapKt.module
